/*CAST*/

SELECT *, 
cast(paymentDate as datetime) as datetime_type
FROM payments;

/*SUBSTRING*/

SELECT CUSTOMERNUMBER,
PAYMENTDATE,
SUBSTRING(PAYMENTDATE, 1,7) AS MONTH_KEY
FROM PAYMENTS;

SELECT CUSTOMERNUMBER,
PAYMENTDATE,
SUBSTRING(PAYMENTDATE, 1,4) AS YEAR_KEY
FROM PAYMENTS;

/*CONCAT*/

SELECT EMPLOYEENUMBER,
LASTNAME,
FIRSTNAME,
CONCAT(firstName, ' ', Lastname) AS FULLNAME
FROM employees;

select customerName, concat(city,", ",country) as location
from customers